[tool.poetry]
name = "impactu"
version = "0.1.0"
description = ""
authors = ["Sim√≥n <simon.garcial@udea.edu.co>"]
readme = "README.md"
packages = [{include = "fast_api_template"}]

[tool.poetry.dependencies]
python = "^3.10"
pydantic = {version = "2.6.2", extras = ["email"]}
flask = "^3.0.0"
odmantic = "1.0.0"
flask-cors = "^4.0.0"
cpi = "^1.0.22"
currencyconverter = "^0.17.13"
pydantic-settings = "^2.2.1"


[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.1"
black = "^23.1.0"
flake8 = "^6.0.0"
debugpy = "^1.8.0"


[tool.poetry.group.test.dependencies]
pytest = "^7.2.1"
pytest-cov = "^4.0.0"
pytest-asyncio = "^0.20.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
